#!/bin/bash

# Simple note taking script

# Get the date
date=$(date)

# Get the topic
topic=$1

# filname to write to
filename="${HOME}/Documents/${topic}notes"

# Ask user for input
read -p "Your note: " note

if [[ $note ]]; then
    echo "$date: $note" >> "$filename"
    echo "Note '$note' saved to $filename"
else
    echo "No input, note wasn't saved!" > 1>&2
fi
